name: Android CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle test
        run: ./gradlew test

      - name: Gradle lint
        run: ./gradlew lint

      - name: Assemble debug
        run: ./gradlew assembleDebug

